### ISSUE TITLE
Not renaming / moving the files (using WSL , folder in windows itself)

### ISSUE THREAD

**Issue by Lowievhb** [drforse/not-llama-fs#6]
![image](https://github.com/drforse/not-llama-fs/assets/107426083/c49569db-89f9-4b9a-a363-0763709fbf84)

**Comment by Lowievhb** [comment]
And how do I run it as an app? Or is it just the demo command

**Comment by drforse** [comment]
It's not really supposed to, as it only has demo mode currently
